### ISSUE TITLE
Invalid links in documentation

### ISSUE THREAD

**Issue by JulienNauroy** [quattor/quattor.github.com#128]
Hi,

I'm browsing the docs at http://quattor-core.readthedocs.org/en/14.10.0/

Some of the links in the "See Also" sections are invalid.
Here's an example : http://quattor-core.readthedocs.org/en/14.10.0/components/aiiserver/
The links to aii-shellfe(8), aii-dhcp(8), aii, ncm-ccm are all invalid.

Cheers,
Julien

**Comment by jrha** [comment]
Hi Julien,

The documentation is generated from the pod files in the `configuration-modules-*` repositories, these links are artefacts from `pod2markdown` you are right though, we should nuke them because they are not helping anyone!

**Comment by wdpypere** [comment]
as discussed on the workshop, broken/dead links and the see also section will be removed in the documentation move.

**Comment by jouvin** [comment]
Highly connected to progress with https://github.com/quattor/release/issues/46...

**Comment by jrha** [comment]
@JulienNauroy I think we've fixed a lot of this as part of #148, #150 and #154, what do you think?

**Comment by JulienNauroy** [comment]
Hi @jrha,

Which version should I check ? The one at
http://quattor-core.readthedocs.org/en/latest/ still has the invalid links.

2015-10-13 23:44 GMT+02:00 James Adams <notifications@github.com>:
