### ISSUE TITLE
Tutorial could list EPEL as a dependency

### ISSUE THREAD

**Issue by JulienNauroy** [quattor/quattor.github.com#129]
I'm trying to follow this tutorial to install Quattor with SCDB : https://trac.lal.in2p3.fr/Quattor/wiki/Download/SCDB
So far, so good.
However, here's a couple of suggestions for section "Quattor Deployment Server":

* the tutorial states that the quattor.repo file should be put in /root/.quattor/yumroot/quattor.repo
Why not write it directly to /etc/yum.repos.d/quattor.repo ?
* EPEL is needed for this part or some packages will be listed as missing (on CentOS 6.6 at least) : perl-CAF, ccm-14.0
You could list there there is (or "may be"? I don't know about SL) a dependency on EPEL. Installing it is as simple as "rpm -ivh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm".

Julien

**Comment by JulienNauroy** [comment]
Here are some more remarks about the dependencies:

* downloading Quattor has (obviously) a dependency on Git.
* Running create-vanilla-SCDB.sh requires java (which version?)
* There's a typo with create-vanilla-SCB.sh => should read SCDB

**Comment by jrha** [comment]
You are correct that EPEL is needed. @jouvin should be able to answer your specific questions about SCDB. I've fixed the typo you spotted.

Thanks!

**Comment by jrha** [comment]
I have added the requirement for EPEL as well, thanks again.

**Comment by JulienNauroy** [comment]
Hi,

Here are some more remarks about the tutorial. Some are more important than others, with no particular order:

 * the packages aii-server and aii-dhcp are not listed in the installation process, while the "Configuration of AII" part requires the packages to be installed
 * the default directory for tftpboot on CentOS is /var/lib/tftpboot. It would be nice to mention it in the "TFTPD configuration" section so that people check the /etc/xinettd.d/tftp file and don't assume /tftpboot is the default on their system
 * There's an extra "svn ci" in the "SCDB Initialization" section, another commit is performed a few lines below. (this one would also require a "-m" in order not to fail)
 * There's a typo in the "Installation of deployment scripts" section: "see SVN server configurion" => configuration
 * Another typo: paramater  => parameter
 * In the "Installation of deployment scripts" section, it is mentioned that "The hook script, post-commit.py must be copied(...)". It should be listed that the script should also be renamed to "post-commit". The "wget" command provided does it.

That's all for now!

**Comment by JulienNauroy** [comment]
A typo I found in SCDB : cfg/standard/features/cvmfs/client-cleanup.pan has a variable named "frecuency"

**Comment by jouvin** [comment]
I'll try to clean the tutorial that should probably be moved as a blog entry in the new web site...

**Comment by jouvin** [comment]
Any feedback on #137 is welcome!
