### ISSUE TITLE
Wiki is historical

### ISSUE THREAD

**Issue by jrha** [quattor/quattor.github.com#136]
As discussed at various workshops, we need to migrate the useful parts of our old wiki to this website and retire the old wiki.

This is a tracker for that process.

**Comment by jouvin** [comment]
I have in mind that for a significant part of what is in the wiki, it would be a better fit to move it to readthedocs.org, as part of the new Quattor documentation we discussed at the Grenoble workshop. This is somewhat related to https://github.com/quattor/release/issues/46 progress.

**Comment by jrha** [comment]
Indeed.

**Comment by stdweird** [comment]
yes
