### ISSUE TITLE
Move meeting summaries to meetings section

### ISSUE THREAD

**Issue by jrha** [quattor/quattor.github.com#179]
Depends on #178.

* Option 1
  * Change category from "news" to "meeting".
  * Add `redirect_from` for old URLs to prevent broken links.
    * e.g. `redirect_from: "/news/2016/03/22/bruxelles-workshop.html".

* Option 2
  * Alternatively, we could change `category: news` to `categories: [news, meeting]`, which would cause each post to exist twice.

**Comment by jrha** [comment]
@gooball next time you are bored you could have a look at this...

**Comment by jouvin** [comment]
@jrha in fact I'd in mind it would break things but thought that probably links to the summary were unlikely to exist... (BTW, I planned to remove documents at the Trac URL but I could also let a redirect if you prefer). It's easy to let something at the old url and redirect to the new one. I'd prefer that all summaries are in the new category as this is the most recent workshops that are affected.

**Comment by jrha** [comment]
I'm not so worried about the Trac, it's been inaccessible for many people for a while now.

Of the two options I prefer adding the `redirect_from` to the front-matter of the posts that get moved, but I'll leave it up to you do decide which is easier.

**Comment by jouvin** [comment]
This is a side issue but I don't understand that people have problems to access Trac... It's up and running, this is one the critical service at LAL...

**Comment by jrha** [comment]
Fixed by #178.
