### ISSUE TITLE
https://www.quattor.org is unusable/untrusted 

### ISSUE THREAD

**Issue by stdweird** [quattor/quattor.github.com#185]
This could be intentional/known/..., but I'm still raising it here
- has www.github.com certificate
- quattor.org is an alias of quattor.github.com?

**Comment by jrha** [comment]
quattor.org is an alias for quattor.github.io as the website is hosted on Github Pages.
We can't do SSL termination properly unless we host the site ourselves or only use quattor.github.io.

How does 16.8 depend on this?

**Comment by stdweird** [comment]
i wanted an answer/statement (esp if this was a bug). it's also relevant for the documentation work (for 16.6) https://github.com/quattor/documentation/pull/2. if `http://quattor.org` is the accepted main url, i have no objections, and we can use it.

**Comment by ned21** [comment]
There is a (free) workaround https://robinwinslow.uk/2016/02/13/free-https-custom-hosting/

**Comment by stdweird** [comment]
There's also https://help.github.com/articles/using-a-custom-domain-with-github-pages/, not sure if this is already configued for quattor

**Comment by jrha** [comment]
I don't like the Cloudflare solution, the connection between Cloudflare and Github remains unencrypted, it doesn't buy us much,

I don't see a problem with sticking to plain HTTP, but if there is a desire for trust, we will have to move the hosting, which shouldn't be too bad (`http://yum.quattor.org` is already at LAL) and might give us more flexibility with the way the site is built anyway.

@stdweird yes, the custom domain is already correctly configured with Github.

**Comment by ned21** [comment]
This is currently not supported by GH, although it has been a requested feature since at least 2014. There's no pressing need for this so we'll continue without https until GH support the feature or there is a clear benefit to migrating the site elsewhere.

**Comment by ned21** [comment]
Github [recently made this possible](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/) so re-opening.

**Comment by jrha** [comment]
I've turned it on and it seems to be working fine, if no-one has any issues then we can close this as solved!

**Comment by stdweird** [comment]
Looks like it's fixed now. It's now handled by `Let's encrypt'
