### ISSUE TITLE
Fix dead links in textrender documentation

### ISSUE THREAD

**Issue by jrha** [quattor/quattor.github.com#196]
- ./_site/documentation/2015/09/20/textrender-basics.html
  *  External link http://docs-test-comps.readthedocs.org/en/latest/CAF/textrender failed: 404 No error
  *  External link http://docs-test-comps.readthedocs.org/en/latest/CCM/textrender failed: 404 No error
  *  External link http://docs-test-maven-tools.readthedocs.org/en/latest/maven-tools/RegexpTest/ failed: 404 No error

- ./_site/documentation/2015/09/22/textrender-outside-metaconfig.html
  *  External link http://docs-test-comps.readthedocs.org/en/latest/CAF/objecttext/#filewriter failed: 404 No error
  *  External link http://docs-test-comps.readthedocs.org/en/latest/CAF/objecttext/#get_text failed: 404 No error

**Comment by wdpypere** [comment]
fixed by https://github.com/quattor/quattor.github.com/pull/198
