### ISSUE TITLE
github-beginners not linked to any page?

### ISSUE THREAD

**Issue by jouvin** [quattor/quattor.github.com#202]
I have the feeling that the page `github-beginners` is not linked to any page... One obvious candidate would be http://www.quattor.org/documentation/2016/03/08/development-basics.html. May be I just missed something or may be the contents of this page is obsolete/not appropriate in which case we should update or remove it....

**Comment by jrha** [comment]
We looked for this at the March 2017 workshop, but couldn't find the page, seems to have been a mistake.

**Comment by jouvin** [comment]
Not sure why I raised this issue, this page obviously doesn't exist.
