### ISSUE TITLE
Move checking of external links to be a manual test

### ISSUE THREAD

**Issue by ned21** [quattor/quattor.github.com#270]
See #269 where travis failed the build due to all links returning 429 (too many requests). This check only makes sense where a human is running it, automated build systems are likely to be blocked.

**Comment by wpoely86** [comment]
Fixed in 3be2e93

**Comment by ned21** [comment]
Still failing, and since I merged the last PR, I am getting emails every few days about this. :(

**Comment by wpoely86** [comment]
About the failing tests in general or the broken links specially?

**Comment by ned21** [comment]
travis seems to re-run the tests on master periodically so if any links fail, it emails me to say the build is broken. Most of the links seem to be fine when I check them (except jenkins0.ugent.be) but it looks like travis is either blocking or being blocked.
